[package]
name = "alien-say"
version = "0.1.0"
authors = ["Kammikazzee <kjell.gudrun-schoke@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
